
let  questions = {
  attemptedStatus: "1",
  currQuesPosition: 1,
  darkMode: 0,
  dataArr: [
  
  
    { //Single Best
      correctAnswer:2,
      ansMarkByUser: "",
      correctMarks: 4,
      incorrectMarks: 1,
      isMultipleOptions: false,
      noOfComponents: 1,
      optionsArr: ["<p>Flexor digitorum profundus</p>", "<p>Lumbricals</p>", "<p>Lumbricals and interossei</p>", "<p>Lumbricals and interossei</p>"],
      quesID: 1,
      quesText: "<p>Hand deformity presennting as hyper-extension at the metcarpo phalaogeal joint and flexion at inter-phalanngeal joint, occurs due to paralysed</p>",
      questionFilter: 1,
      sectionName: "Section 1",
      uniqueTimer: 0,
      visited:true,
      review:false,
      status:0,
      noAnswer:"#",
      ansreview:false
    },
    { //Single Best
      correctAnswer:3,
      ansMarkByUser: "",
      correctMarks: 4,
      incorrectMarks: 1,
      isMultipleOptions: false,
      noOfComponents: 1,
      optionsArr: ["<p>Flexor digitorum profundus</p>", "<p>Lumbricals</p>", "<p>Lumbricals and interossei</p>", "<p>Lumbricals and interossei</p>"],
      quesID: 1,
      quesText: "<p> Which of the following are the advantages of React.js?</p>",
      questionFilter: 1,
      sectionName: "Section 1",
      uniqueTimer: 0,
      visited:false,
      review:false,
      status:0,
      noAnswer:"",
      ansreview:false
    },
    {// Multiple Correct
      correctAnswer:4,
      ansMarkByUser: "",
      correctMarks: 4,
      incorrectMarks: 1,
      isMultipleOptions: true,
      noOfComponents: 1,
      optionsArr: ["<p>React.js</p>", "<p>ReactJs</p>", "<p>All of the Above</p>","<p>REACT.js</p>"],
      quesID: 2,
      quesText: "<p>Which of the following are the advantages of React.js?</p>",
      questionFilter: 1,
      sectionName: "Section 1",
      uniqueTimer: 0,
      visited:false,
      review:false,
      status:0,
      noAnswer:"",
      ansreview:false
    },
     {//tf
      quesID: 2907,
      ansMarkByUser: "",
      quesText: `<style type="text/css">.blueText,.grayText,.greenText,.redText{display:block!important}.optionTable{margin:0 0 10px;border-radius:10px;box-shadow:1px 1px 5px 0 #ddd;background-color:#fff}.optionTableTdStyle{padding-left:0;padding-top:0;padding-bottom:0;position:relative}.optionTableGray{border:thin solid #ddd!important}.optionTableBlue{border:thin solid #479cd3!important}.optionTableGreenSolution{border:thin solid #80c244!important}.optionTableGreen{border:thin solid #80c244!important;background-color:#f0f8e9}.optionTableRed{border:thin solid #da5b59!important;background-color:#fcf4f4}.optionLabel{color:#fff;border-radius:50%;width:20px;height:20px;font-weight:700;font-size:50%;text-align:center;line-height:20px}.optionLabelGray{background-color:#474747}.optionLabelBlue{background-color:#479cd3 !important}.optionLabelGreen{background-color:#80c244 !important}.optionLabelRed{background-color:#da5b59 !important}.optionStats{position:absolute;right:5px;font-size:60%}.optionTopStats{top:5px}.optionBottomStats{bottom:2px;font-weight:700}.grayText{color:#474747}.blueText{color:#479cd3}.greenText{color:#80c244}.redText{color:#da5b59}.table-striped>tbody>tr:nth-child(odd)>td,.table-striped>tbody>tr:nth-child(odd)>th{background-color:rgba(184,218,255,.2)!important}.table-striped>tbody>tr:nth-child(even)>td,.table-striped>tbody>tr:nth-child(even)>th{background-color:#fff!important;color:#333}.table{width:100%;margin:15px 0;border:none}.borderless td,.borderless th{border-bottom:none;border-left:none;border-top:none;padding:10px}.ulClass{list-style-type:none;padding-left:0}.ulClass li{margin:10px 0}.ulClass li:before{background-color:#128adc;border-radius:50%;content:"";display:inline-block;margin-right:10px;margin-bottom:2px;height:6px;width:6px}.smallOption{font-size:75%}.smallOptionLabel{width:15px;height:15px;line-height:15px}.table-striped>tbody>tr:nth-child(1)>td,.table-striped>tbody>tr:nth-child(1)>th{background-color:rgba(184,218,255,.8)!important}.ulClass .liClass .ulClass {padding-left: 20px !important}</style><p><span>The following statements are true/false regarding homeostasis: </span></p>`,
      optionsArr: [
          "<p><span>Homeostasis means the maintenance of nearly constant conditions in the body </span></p>",
          "<p><span>In most diseases, homeostatic mechanisms are no longer operating in the body </span></p>",
          "<p><span>Disease is generally considered to be a state of disrupted homeostasis </span></p>",
          "<p><span>Walter Cannon introduce the concept of &lsquo;internal environment of the body&rsquo; </span></p>",
          "<p><span>Claude Bernard coined the term &lsquo;Homeostasis&rsquo; </span></p>"
      ],
      sectionName: "anatomy",
    
      uniqueTimer: 0,
      noOfComponents: 1,
      isMultipleOptions:false,
      questionFilter:2
  },
  {
    quesID: 2908,
    ansMarkByUser: "",
    quesTags: "Tag 1, Tag 2, Tag 3",
    quesTextHighlight: "<p>A patient has the pink papules and plaques over genital. What serotype of human papilloma virus (HPV) is the most likely cause?</p>",
    quesText: "<style type=\"text/css\">.blueText,.grayText,.greenText,.redText{display:block!important}.optionTable{margin:0 0 10px;border-radius:10px;box-shadow:1px 1px 5px 0 #ddd;background-color:#fff}.optionTableTdStyle{padding-left:0;padding-top:0;padding-bottom:0;position:relative}.optionTableGray{border:thin solid #ddd!important}.optionTableBlue{border:thin solid #479cd3!important}.optionTableGreenSolution{border:thin solid #80c244!important}.optionTableGreen{border:thin solid #80c244!important;background-color:#f0f8e9}.optionTableRed{border:thin solid #da5b59!important;background-color:#fcf4f4}.optionLabel{color:#fff;border-radius:50%;width:20px;height:20px;font-weight:700;font-size:50%;text-align:center;line-height:20px}.optionLabelGray{background-color:#474747}.optionLabelBlue{background-color:#479cd3 !important}.optionLabelGreen{background-color:#80c244 !important}.optionLabelRed{background-color:#da5b59 !important}.optionStats{position:absolute;right:5px;font-size:60%}.optionTopStats{top:5px}.optionBottomStats{bottom:2px;font-weight:700}.grayText{color:#474747}.blueText{color:#479cd3}.greenText{color:#80c244}.redText{color:#da5b59}.table-striped>tbody>tr:nth-child(odd)>td,.table-striped>tbody>tr:nth-child(odd)>th{background-color:rgba(184,218,255,.2)!important}.table-striped>tbody>tr:nth-child(even)>td,.table-striped>tbody>tr:nth-child(even)>th{background-color:#fff!important;color:#333}.table{width:100%;margin:15px 0;border:none}.borderless td,.borderless th{border-bottom:none;border-left:none;border-top:none;padding:10px}.ulClass{list-style-type:none;padding-left:0}.ulClass li{margin:10px 0}.ulClass li:before{background-color:#128adc;border-radius:50%;content:\"\";display:inline-block;margin-right:10px;margin-bottom:2px;height:6px;width:6px}.smallOption{font-size:75%}.smallOptionLabel{width:15px;height:15px;line-height:15px}.table-striped>tbody>tr:nth-child(1)>td,.table-striped>tbody>tr:nth-child(1)>th{background-color:rgba(184,218,255,.8)!important}</style><p>Match the following:</p>\r\n<table cellspacing=\"0\" class=\"borderless table table-striped table-responsive\" border=\"1\">\r\n<tbody>\r\n<tr>\r\n<td><strong>DISEASE </strong></td>\r\n<td><strong>INCLUSION</strong></td>\r\n</tr>\r\n<tr>\r\n<td>1. HSV</td>\r\n<td>a. Lewy body</td>\r\n</tr>\r\n<tr>\r\n<td>2. Parkinson&rsquo;s disease</td>\r\n<td>b. Mallory bodies</td>\r\n</tr>\r\n<tr>\r\n<td>3. Alcoholic hepatitis</td>\r\n<td>c. Negri bodies</td>\r\n</tr>\r\n<tr>\r\n<td>4. Rabies</td>\r\n<td>d. Cowdry type A</td>\r\n</tr>\r\n</tbody>\r\n</table>",
    optionsArr: ["", "", "", ""],
    solutions: "<p>C/o of Anogenital warts- cause by HPV 6</p><table><tbody><tr><td><strong>HPV type</strong></td><td><strong>Associated clinical conditions</strong></td></tr><tr><td>1 (m/c)</td><td><strong>D</strong>eep plantar and palmar warts</td></tr><tr><td>2 (m/c)</td><td><strong>S</strong>uperficial plantar warts</td></tr><tr><td>3</td><td><strong>P</strong>lane warts</td></tr><tr><td>4</td><td><strong>C</strong>ommon warts, plantar warts</td></tr><tr><td>5</td><td><strong>E</strong>pidermo dysplasia verruciformis</td></tr><tr><td>6 (m/c)</td><td><strong>L</strong>aryngeal warts<strong>, Anogenital warts</strong></td></tr><tr><td>7 (m/c)</td><td><strong>B</strong>utcher wart</td></tr></tbody></table><p>Mnemonic: DSP- CELB</p>",
    reference: "<p>Rook&rsquo;s textbook of dermatology 7th/ table 25.38</p>",
    correctAns: "1a,2b,3c,4d",
    
    overAllMarker: { 1: 7, 2: 25, 3: 3, 4: 65, totalAttempts: 2364 },
    timerForQues: 30,
    askDoubt: 1,
    isQuesVideoSolution: 0,
    quesType: 1,
    isBookmarked: 0,
    treasureHtml: "",
    treasureID: "0",
    sectionID: 20,
    isMultipleOptions: false,
    noOfComponents: 4,
    questionFilter: 3
  },
       {//theme type
        quesID: 2909,
        quesTags: "Tag 1, Tag 2, Tag 3",
        quesTextHighlight: "<p>A patient has the pink papules and plaques over genital. What serotype of human papilloma virus (HPV) is the most likely cause?</p>",
        quesText: "<style type=\"text/css\">.blueText,.grayText,.greenText,.redText{display:block!important}.optionTable{margin:0 0 10px;border-radius:10px;box-shadow:1px 1px 5px 0 #ddd;background-color:#fff}.optionTableTdStyle{padding-left:0;padding-top:0;padding-bottom:0;position:relative}.optionTableGray{border:thin solid #ddd!important}.optionTableBlue{border:thin solid #479cd3!important}.optionTableGreenSolution{border:thin solid #80c244!important}.optionTableGreen{border:thin solid #80c244!important;background-color:#f0f8e9}.optionTableRed{border:thin solid #da5b59!important;background-color:#fcf4f4}.optionLabel{color:#fff;border-radius:50%;width:20px;height:20px;font-weight:700;font-size:50%;text-align:center;line-height:20px}.optionLabelGray{background-color:#474747}.optionLabelBlue{background-color:#479cd3 !important}.optionLabelGreen{background-color:#80c244 !important}.optionLabelRed{background-color:#da5b59 !important}.optionStats{position:absolute;right:5px;font-size:60%}.optionTopStats{top:5px}.optionBottomStats{bottom:2px;font-weight:700}.grayText{color:#474747}.blueText{color:#479cd3}.greenText{color:#80c244}.redText{color:#da5b59}.table-striped>tbody>tr:nth-child(odd)>td,.table-striped>tbody>tr:nth-child(odd)>th{background-color:rgba(184,218,255,.2)!important}.table-striped>tbody>tr:nth-child(even)>td,.table-striped>tbody>tr:nth-child(even)>th{background-color:#fff!important;color:#333}.table{width:100%;margin:15px 0;border:none}.borderless td,.borderless th{border-bottom:none;border-left:none;border-top:none;padding:10px}.ulClass{list-style-type:none;padding-left:0}.ulClass li{margin:10px 0}.ulClass li:before{background-color:#128adc;border-radius:50%;content:\"\";display:inline-block;margin-right:10px;margin-bottom:2px;height:6px;width:6px}.smallOption{font-size:75%}.smallOptionLabel{width:15px;height:15px;line-height:15px}.table-striped>tbody>tr:nth-child(1)>td,.table-striped>tbody>tr:nth-child(1)>th{background-color:rgba(184,218,255,.8)!important}</style><p><strong>Theme &amp; Focus: GI hormones and motility</strong></p>\r\n<p>Gastro-colic reflex</p>..::::..<p>Receptive relaxation</p>..::::..<p>Receptive relaxation</p>..::::..<p>Receptive relaxation</p>",
        optionsArr: [
            "<p>Release of cholecystokinin</p>",
            "<p>Distension of the viscus wall</p>",
            "<p>Release of secretin</p>",
            "<p>Release of gastrin</p>",
            "<p>Release of motilin</p>"
        ],
        solutions: "<p>C/o of Anogenital warts- cause by HPV 6</p><table><tbody><tr><td><strong>HPV type</strong></td><td><strong>Associated clinical conditions</strong></td></tr><tr><td>1 (m/c)</td><td><strong>D</strong>eep plantar and palmar warts</td></tr><tr><td>2 (m/c)</td><td><strong>S</strong>uperficial plantar warts</td></tr><tr><td>3</td><td><strong>P</strong>lane warts</td></tr><tr><td>4</td><td><strong>C</strong>ommon warts, plantar warts</td></tr><tr><td>5</td><td><strong>E</strong>pidermo dysplasia verruciformis</td></tr><tr><td>6 (m/c)</td><td><strong>L</strong>aryngeal warts<strong>, Anogenital warts</strong></td></tr><tr><td>7 (m/c)</td><td><strong>B</strong>utcher wart</td></tr></tbody></table><p>Mnemonic: DSP- CELB</p>",
        reference: "<p>Rook&rsquo;s textbook of dermatology 7th/ table 25.38</p>",
        correctAns: "1,2,3,3",
        ansMarkByUser: "",
        overAllMarker: { 1: 7, 2: 25, 3: 3, 4: 5, totalAttempts: 2364 },
        timerForQues: 30,
        askDoubt: 1,
        isQuesVideoSolution: 0,
        quesType: 1,
        noOfComponents: 1,
        isBookmarked: 0,
        treasureHtml: "",
        treasureID: "0",
        sectionID: 20,
        isMultipleOptions: false,
        noOfComponents: 1,
        questionFilter: 4
    },
    {
    quesID: 2912,
    ansMarkByUser: "",
    quesTags: "",
    quesTextHighlight: `<p><span style="color:#231F20;">Surya Ltd has provided you the following particulars. Prepare Cash Flow from Operating Activities by Indirect Method in accordance with AS 3 :</span></p><p><span style="color:#231F20;">Profit &amp; Loss Account of Surya Ltd. <strong>for the year ended 31st March, 2013</strong></span></p><figure class="table" style="float:left;"><table style="border-bottom:none;border-left:none;border-right:none;border-top:none;"><tbody><tr><td style="background-color:#DCDDDE;border-bottom:1.0pt solid #231F20;border-left:1.0pt solid #231F20;border-right:1.0pt solid #231F20;border-top:1.0pt solid #231F20;height:20.55pt;padding:0cm;vertical-align:top;width:156.65pt;"><p style="text-align:center;"><span style="color:#231F20;"><strong>Particulars</strong></span></p></td><td style="background-color:#DCDDDE;border-bottom:1.0pt solid #231F20;border-left:1.0pt none #231F20;border-right:1.0pt solid #231F20;border-top:1.0pt solid #231F20;height:20.55pt;padding:0cm;vertical-align:top;width:97.3pt;"><p style="text-align:center;"><span style="color:#231F20;"><strong>Rs</strong></span></p></td><td style="background-color:#DCDDDE;border-bottom:1.0pt solid #231F20;border-left:1.0pt none #231F20;border-right:1.0pt solid #231F20;border-top:1.0pt solid #231F20;height:20.55pt;padding:0cm;vertical-align:top;width:142.65pt;"><p style="text-align:center;"><span style="color:#231F20;"><strong>Particulars</strong></span></p></td><td style="background-color:#DCDDDE;border-bottom:1.0pt solid #231F20;border-left:1.0pt none #231F20;border-right:1.0pt solid #231F20;border-top:1.0pt solid #231F20;height:20.55pt;padding:0cm;vertical-align:top;width:108.3pt;"><p style="text-align:center;"><span style="color:#231F20;"><strong>Rs</strong></span></p></td></tr><tr><td style="border-bottom:1.0pt solid #231F20;border-left:1.0pt solid #231F20;border-right:1.0pt solid #231F20;border-top:1.0pt none #231F20;height:196.55pt;padding:0cm;vertical-align:top;width:156.65pt;"><p><span style="color:#231F20;">To Depreciation</span></p><p><span style="color:#231F20;">To Patents written off</span></p><p><span style="color:#231F20;">To Provision for Tax&nbsp;</span></p><p><span style="color:#231F20;">To Proposed dividend</span></p><p><span style="color:#231F20;">To Transfer to Reserve&nbsp;</span></p><p><span style="color:#231F20;">To Net Profit</span></p></td><td style="border-bottom:1.0pt solid #231F20;border-left:none;border-right:1.0pt solid #231F20;border-top:none;height:196.55pt;padding:0cm;vertical-align:top;width:97.3pt;"><p style="text-align:center;"><span style="color:#231F20;">86,700</span></p><p style="text-align:center;">&nbsp;</p><p style="text-align:center;"><span style="color:#231F20;">35,000</span></p><p style="text-align:center;"><span style="color:#231F20;">1,25,000</span></p><p style="text-align:center;"><span style="color:#231F20;">`,
    quesText: `<p><span>\(\begin{equation} p \wedge p \equiv p \end{equation}\)</span></p><p><span style="color:#231F20;">Surya Ltd has provided you the following particulars. Prepare Cash Flow from Operating Activities by Indirect Method in accordance with AS 3 :</span></p><p><span style="color:#231F20;">Profit &amp; Loss Account of Surya Ltd. <strong>for the year ended 31st March, 2013</strong></span></p><figure class="table" style="float:left;"><table style="border-bottom:none;border-left:none;border-right:none;border-top:none;"><tbody><tr><td style="background-color:#DCDDDE;border-bottom:1.0pt solid #231F20;border-left:1.0pt solid #231F20;border-right:1.0pt solid #231F20;border-top:1.0pt solid #231F20;height:20.55pt;padding:0cm;vertical-align:top;width:156.65pt;"><p style="text-align:center;"><span style="color:#231F20;"><strong>Particulars</strong></span></p></td><td style="background-color:#DCDDDE;border-bottom:1.0pt solid #231F20;border-left:1.0pt none #231F20;border-right:1.0pt solid #231F20;border-top:1.0pt solid #231F20;height:20.55pt;padding:0cm;vertical-align:top;width:97.3pt;"><p style="text-align:center;"><span style="color:#231F20;"><strong>Rs</strong></span></p></td><td style="background-color:#DCDDDE;border-bottom:1.0pt solid #231F20;border-left:1.0pt none #231F20;border-right:1.0pt solid #231F20;border-top:1.0pt solid #231F20;height:20.55pt;padding:0cm;vertical-align:top;width:142.65pt;"><p style="text-align:center;"><span style="color:#231F20;"><strong>Particulars</strong></span></p></td><td style="background-color:#DCDDDE;border-bottom:1.0pt solid #231F20;border-left:1.0pt none #231F20;border-right:1.0pt solid #231F20;border-top:1.0pt solid #231F20;height:20.55pt;padding:0cm;vertical-align:top;width:108.3pt;"><p style="text-align:center;"><span style="color:#231F20;"><strong>Rs</strong></span></p></td></tr><tr><td style="border-bottom:1.0pt solid #231F20;border-left:1.0pt solid #231F20;border-right:1.0pt solid #231F20;border-top:1.0pt none #231F20;height:196.55pt;padding:0cm;vertical-align:top;width:156.65pt;"><p><span style="color:#231F20;">To Depreciation</span></p><p><span style="color:#231F20;">To Patents written off</span></p><p><span style="color:#231F20;">To Provision for Tax&nbsp;</span></p><p><span style="color:#231F20;">To Proposed dividend</span></p><p><span style="color:#231F20;">To Transfer to Reserve&nbsp;</span></p><p><span style="color:#231F20;">To Net Profit</span></p></td><td style="border-bottom:1.0pt solid #231F20;border-left:none;border-right:1.0pt solid #231F20;border-top:none;height:196.55pt;padding:0cm;vertical-align:top;width:97.3pt;"><p style="text-align:center;"><span style="color:#231F20;">86,700</span></p><p style="text-align:center;">&nbsp;</p><p style="text-align:center;"><span style="color:#231F20;">35,000</span></p><p style="text-align:center;"><span style="color:#231F20;">1,25,000</span></p><p style="text-align:center;"><span style="color:#231F20;">`,
    optionsArr: [
        "",
        "",
        "",
        "",
        ""
    ],
    solutions: "<p>C/o of Anogenital warts- cause by HPV 6</p><table><tbody><tr><td><strong>HPV type</strong></td><td><strong>Associated clinical conditions</strong></td></tr><tr><td>1 (m/c)</td><td><strong>D</strong>eep plantar and palmar warts</td></tr><tr><td>2 (m/c)</td><td><strong>S</strong>uperficial plantar warts</td></tr><tr><td>3</td><td><strong>P</strong>lane warts</td></tr><tr><td>4</td><td><strong>C</strong>ommon warts, plantar warts</td></tr><tr><td>5</td><td><strong>E</strong>pidermo dysplasia verruciformis</td></tr><tr><td>6 (m/c)</td><td><strong>L</strong>aryngeal warts<strong>, Anogenital warts</strong></td></tr><tr><td>7 (m/c)</td><td><strong>B</strong>utcher wart</td></tr></tbody></table><p>Mnemonic: DSP- CELB</p>",
    reference: "<p>Rook&rsquo;s textbook of dermatology 7th/ table 25.38</p>",
    correctAns: "78.0",
  
    overAllMarker: { 1: 7, 2: 25, 3: 3, 4: 65, totalAttempts: 2364 },
    timerForQues: 30,
    askDoubt: 1,
    isQuesVideoSolution: 0,
    quesType: 1,
    noOfComponents: 1,
    isBookmarked: 0,
    treasureHtml: "",
    treasureID: "0",
    sectionID: 20,
    isMultipleOptions: false,
    noOfComponents: 3,
    questionFilter: 8

  }

  ]
}

// let questions =
// [
//   {
//     id: 1,
//     question: " Which of the following are the advantages of React.js?" ,
//     selectedAnswer:"f",
//     answer: 4,
//     status:0,
//     visited:true,
//     review:false,
//     options:[
//       // "<p>Option</p>"
//       { id: 2, name: "React.js" },
//       { id: 3, name: "ReactJs" },
//       { id: 4, name: "All of the Above" },
//     ],
//   },
//   {
//     id: 2,
//     question: " Which of the following are the advantages of React.js?",
//     selectedAnswer:"",
//     answer: 4,
//     status:0,
//     review:false,
//     visited:false,
//     options: [
//       { id: 1, name: "React.js can increase the application's performance with Virtual DOM." },
//       { id: 2, name: "React.js is easy to integrate with other frameworks such as Angular, BackboneJS since it is only a view library." },
//       { id: 3, name: "React.js can render both on client and server side." },
//       { id: 4, name: "All of the above" },
//     ],
//   },
//   {
//     id: 3,
//     question: "How many numbers of elements a valid react component can return?",
//     selectedAnswer:"",
//     answer: 1,
//     status:0,
//     visited:false,
//     review:false,
//     options: [
//       { id: 1, name: "1" },
//       { id: 2, name: "2" },
//       { id: 3, name: "4" },
//       { id: 4, name: "5" },
//     ],
//   },
//   {
//     id: 4,
//     question: "What is the declarative way to render a dynamic list of components based on values in an array?",
//     selectedAnswer:"",
//     answer: 2,
//     status:0,
//     visited:false,
//     review:false,
//     options: [
//       { id: 1, name: "Using the reduce array method" },
//       { id: 2, name: "Using the <Each /> component" },
//       { id: 3, name: "Using the Array.map() method" },
//       { id: 4, name: "With a for/while loop" },
//     ],
//   },
//   {
//     id: 5,
//     question: "  How many ways of defining your variables in ES6?",
//     selectedAnswer:"",
//     answer: 2,
//     status:0,
//     visited:false,
//     review:false,
//     options: [
//       { id: 1, name: "1" },
//       { id: 2, name: "3" },
//       { id: 3, name: "4" },
//       { id: 4, name: "5" },
//     ],
//   },
//   {
//     id: 6,
//     question: " What is a state in React?",
//     selectedAnswer:"",
//     answer: 2,
//     status:0,
//     visited:false,
//     review:false,
//     options: [
//       { id: 1, name: "A permanent storage." },
//       { id: 2, name: "Internal storage of the component." },
//       { id: 3, name: "External storage of the component." },
//       { id: 4, name: "None of the above." },
//     ],
//   },
//   {
//     id: 7,
//     question: " What are the two ways to handle data in React?",
//     selectedAnswer:"",
//     answer: 1,
//     status:0,
//     visited:false,
//     review:false,
//     options: [
//       { id: 1, name: "State & Props" },
//       { id: 2, name: "Services & Components" },
//       { id: 3, name: "State & Services" },
//       { id: 4, name: "State & Component" },
//     ],
//   },
//   {
//     id: 8,
//     question: " In which of the following directory React.js components are saved?",
//     selectedAnswer:"",
//     answer: 1,
//     status:0,
//     visited:false,
//     review:false,
//     options: [
//       { id: 1, name: "Inside the js/components/" },
//       { id: 2, name: "Inside the vendor/components/" },
//       { id: 3, name: "Inside the external/components/" },
//       { id: 4, name: "Inside the vendor/" },
//     ],
//   },
//   {
//     id: 9,
//     question: ". Which of the following acts as the input of a class-based component?",
//     selectedAnswer:"",
//     answer: 2,
//     status:0,
//     visited:false,
//     review:false,
//     options: [
//       { id: 1, name: "class" },
//       { id: 2, name: "props" },
//       { id: 3, name: "Factory" },
//       { id: 4, name: "None of the mentioned" },
//     ],
//   },
//   {
//     id: 10,
//     question: " React.js is written in which of the following language?",
//     selectedAnswer:"",
//     answer: 3 ,
//     status:0,
//     visited:false,
//     review:false,
//     options: [
//       { id: 1, name: "C" },
//       { id: 2, name: "C++" },
//       { id: 3, name: "Java" },
//       { id: 4, name: "Javascript" },
//     ],
//   },
//   {
//     id: 11,
//     question: " How many elements can a valid react component return?",
//     selectedAnswer:"",
//     answer: 1,
//     status:0,
//     visited:false,
//     review:false,
//     options: [
//       { id: 1, name: " Inside js/components/" },
//       { id: 2, name: "Inside components/js/" },
//       { id: 3, name: " Inside vendor/js/components/" },
//       { id: 4, name: "Inside vendor/components/" },
//     ],
//   },
//   {
//     id: 12,
//     question: "  Which of the following is method is not a part of ReactDOM?",
//     selectedAnswer:"",
//     answer: 2,
//     status:0,
//     visited:false,
//     review:false,
//     options: [
//       { id: 1, name: " ReactDOM.hydrate()" },
//       { id: 2, name: "ReactDOM.destroy()" },
//       { id: 3, name: "ReactDOM.createPortal()" },
//       { id: 4, name: " All of the mentioned" },
//     ],
//   },
//   {
//     id: 13,
//     question: "  Which of the following is used to pass data to a component from outside in React?",
//     selectedAnswer:"",
//     answer: 2,
//     status:0,
//     visited:false,
//     review:false,
//     options: [
//       { id: 1, name: "props" },
//       { id: 2, name: "render with arguments" },
//       { id: 3, name: "setState" },
//       { id: 4, name: " PropTypes" },
//     ],
//   },
//   {
//     id: 14,
//     question: " Which of the following are the advantages of React.js?",
//     selectedAnswer:"",
//     answer: 2,
//     status:0,
//     visited:false,
//     review:false,
//     options: [
//       { id: 1, name: "React.js can increase the application's performance with Virtual DOM." },
//       { id: 2, name: "React.js is easy to integrate with other frameworks such as Angular, BackboneJS since it is only a view library." },
//       { id: 3, name: "React.js can render both on client and server side." },
//       { id: 4, name: "All of the above" },
//     ],
//   },
//   {
//     id: 15,
//     question: " Which of the following are the advantages of React.js?",
//     selectedAnswer:"",
//     answer: 2,
//     status:0,
//     visited:false,
//     review:false,
//     options: [
//       { id: 1, name: "React.js can increase the application's performance with Virtual DOM." },
//       { id: 2, name: "React.js is easy to integrate with other frameworks such as Angular, BackboneJS since it is only a view library." },
//       { id: 3, name: "React.js can render both on client and server side." },
//       { id: 4, name: "All of the above" },
//     ],
//   },
//   {
//     id: 16,
//     question: " Which of the following are the advantages of React.js?",
//     selectedAnswer:"",
//     answer: 2,
//     status:0,
//     visited:false,
//     review:false,
//     options: [
//       { id: 1, name: "React.js can increase the application's performance with Virtual DOM." },
//       { id: 2, name: "React.js is easy to integrate with other frameworks such as Angular, BackboneJS since it is only a view library." },
//       { id: 3, name: "React.js can render both on client and server side." },
//       { id: 4, name: "All of the above" },
//     ],
//   },
//   {
//     id: 17,
//     question: " Which ReactJS function renders HTML to the web page?",
//     selectedAnswer:"",
//     answer: 2,
//     status:0,
//     visited:false,
//     review:false,
//     options: [
//       { id: 1, name: "render()" },
//       { id: 2, name: "ReactDOM.render()" },
//       { id: 3, name: "renders()" },
//       { id: 4, name: "ReactDOM.renders()" },
//     ],
//   },
//     {
//     id: 18,
//     question: "What is the default port where webpack-server runs?",
//     selectedAnswer:"",
//     answer: 2,
//     status:0,
//     visited:false,
//     review:false,
//     options: [
//       { id: 1, name: "3000" },
//       { id: 2, name: "8080" },
//       { id: 3, name: "3030" },
//       { id: 4, name: "All of the above" },
//     ],
//   },
// ];
export default questions




